"""added banned field to user model

Revision ID: 0d5a130276a1
Revises: 3b979de04914
Create Date: 2025-12-19 19:20:39.065875

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5a130276a1'
down_revision: Union[str, Sequence[str], None] = '3b979de04914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('is_banned', sa.BOOLEAN(), nullable=True))
    
    op.execute("UPDATE users SET is_banned = false WHERE is_banned IS NULL")
    
    op.alter_column('users', 'is_banned', nullable=False, server_default=False)    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
