"""make username unique

Revision ID: 692db0042468
Revises: 0d5a130276a1
Create Date: 2025-12-24 17:32:39.827832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692db0042468'
down_revision: Union[str, Sequence[str], None] = '0d5a130276a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username_unique', sa.String(), nullable=True))
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE users u1
        SET username_unique = 
            CASE WHEN u2.rn = 1 THEN u1.username 
                 ELSE u1.username || '_' || (u2.rn - 1)::text 
            END
        FROM (
            SELECT id, username,
                   ROW_NUMBER() OVER (PARTITION BY username ORDER BY id) as rn
            FROM users
        ) u2
        WHERE u1.id = u2.id
    """))
    op.drop_column('users', 'username')
    op.alter_column('users', 'username_unique', new_column_name='username')
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_user_username', 'users', type_='unique')
    # ### end Alembic commands ###
